core/urls.py
from django.urls import path
from core.views import student_login, index, check_result, my_result, student_logout


app_name ='core'

urlpatterns = [
    path("", index, name='index'),
    path("login", student_login, name='login'),
    path("logout", student_logout, name='logout'),
    path('check-results/', check_result, name='check_result'),
    path('my-result/<int:session_id>/<int:semester_id>/', my_result, name='result_page'),
    
    
]

result/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
import random
import string

import string, random
from django.db import models

class Student(models.Model):
    reg_number = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True, blank=True, null=True)
    password = models.CharField(max_length=100, blank=True, help_text="Leave blank to auto-generate a password.")  # plain text password (not secure!)

    def save(self, *args, **kwargs):
        if not self.password:  # Only generate if no password is set
            chars = string.ascii_letters + string.digits
            self.password = ''.join(random.choice(chars) for _ in range(8))
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f"{self.reg_number} - {self.name}"
        

# Course model (optional but useful)
class Course(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10, unique=True)  # e.g., "CSC101"

    def __str__(self):
        return f"{self.code} - {self.name}"
    
class Session(models.Model):
    name = models.CharField(max_length=100, help_text="eg 2024/2025")  # e.g., "2024/2025"
    def __str__(self):
        return self.name

class Semester(models.Model):
    name = models.CharField(max_length=20, help_text="eg First semester or Second")  # e.g., "First", "Second"
    def __str__(self):
        return self.name
    
# Result model
class Result(models.Model):
    GRADE_CHOICES = [
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("D", "D"),
        ("E", "E"),
        ("F", "F"),
    ]
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    score = models.FloatField(blank=True, null=True)
    grade = models.CharField(max_length=2, choices=GRADE_CHOICES, blank=True, null=True)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)  # e.g., "2024/2025"

    class Meta:
        unique_together = ("student", "course", "semester", "session")

    def __str__(self):
        return f"{self.student.reg_number} - {self.course.code} - {self.score}"
    



core/forms.py
# dashboard/forms.py
from django import forms
from .models import  Semester, Session


class CheckResult(forms.Form):
    session = forms.ModelChoiceField(
    queryset=Session.objects.all(),
    empty_label="Select a session",
    required=True,
    widget=forms.Select(attrs={'class': 'form-select'})
)

    semester = forms.ModelChoiceField(
    queryset=Semester.objects.all(), 
    empty_label="Select a Semester",
    required=True,  
    widget=forms.Select(attrs={'class': 'form-select'}))

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Student, Result
from core.forms import CheckResult
from django.contrib.auth.decorators import login_required
from core.utils import student_login_required



@student_login_required
def index(request):
    
    return render(request, "dashboard/index.html")

def student_login(request):
    if request.method == "POST":
        reg_number = request.POST.get("reg_number")
        password = request.POST.get("password")

        try:
            student = Student.objects.get(reg_number=reg_number, password=password)
            # Save session
            request.session["student_id"] = student.id
            request.session["student_name"] = student.name
            return redirect("core:index")  # redirect to dashboard
        except Student.DoesNotExist:
            messages.error(request, "Invalid Registration Number or Password")

    return render(request, "dashboard/login.html")


@student_login_required
def student_dashboard(request):
    student_id = request.session.get("student_id")
    student = Student.objects.get(id=student_id)

    return render(request, "dashboard/index.html", {"student": student})


@student_login_required
def check_result(request):
    if request.method == 'POST':
        form = CheckResult(request.POST)
        if form.is_valid():
            session = form.cleaned_data['session'].id
            semester = form.cleaned_data['semester'].id

            return redirect('core:result_page', session_id=session, semester_id=semester)
    else:
        form = CheckResult()

    return render(request, "dashboard/check_result.html", {'form': form})


@student_login_required
def my_result(request, session_id, semester_id):
    # get student from session
    student_id = request.session.get("student_id")
    if not student_id:
        return redirect("dashboard:student_login")

    student = Student.objects.get(id=student_id)

    results = Result.objects.filter(
        student=student,
        session_id=session_id,
        semester_id=semester_id
    ).select_related('course')

    if not results.exists():
        messages.error(request, "Result not found for the selected session and semester.")
        return redirect('core:check_result')

    context = {
        'results': results,
        'student': student,
        'session': results.first().session,
        'semester': results.first().semester,
    }
    return render(request, 'dashboard/result_page.html', context)


def student_logout(request):
    request.session.flush()
    return redirect("core:login")

templates/dashboard/check_result.html
{% extends "include/base.html"%}

{% block content%}
{% load static %}

<main class="main" id="main">
  <div class="container mt-5">
    <h4 class="fw-bold text-purple border-bottom pb-2 mb-4">Check Result</h4>

    <form method="post"  class="mx-auto" style="max-width: 500px;">
        {% csrf_token %}
      <!-- Session Dropdown -->
      <div class="mb-4">
        <label for="session" class="form-label">Session</label>
        {{ form.session}}
      </div>

      <!-- Payment Type Dropdown -->
      <div class="mb-4">
        <label for="payment_type" class="form-label">Semester:</label>
        {{form.semester}}
      </div>

      <!-- Pay Button -->
      <div class="text-center">
        <button type="submit" class="btn btn-danger px-5">Submit</button>
      </div>
    </form>
  </div>
</main>


{% endblock content %}

templates/dashboard/index.html
{% extends "include/base.html"%}

{% block content%}
{% load static %}


  <main id="main" class="main">

    <div class="pagetitle mb-5 d-flex justify-content-between align-items-center">
      <div>
          <h1>Overview</h1>
          <p>Good Day, {{ request.session.student_name }}.</p>
      </div>
      <div class="d-flex align-items-center bg-light p-2 rounded border" id="calendarTrigger">
          <i class="bi bi-calendar me-2"></i>
          <div>
              <small class="text-muted">Today's Date</small>
              <input type="text" id="datepicker" class="border-0 bg-light" value="13th January, 2025" readonly>
          </div>
      </div>
  </div><!-- End Page Title -->
  <section class="section dashboard">
    <div class="row g-4">
      <!-- Card 1: Total Number of Students -->
      <div class="col-md-6">
         <h1>Need Help?</h1>
         <p>
            If you are a new student, kindly follow these steps.<br>
            Check result
         </p>
      </div>

      <!-- Card 2: Attendance Percentage -->
     <div class="col-md-6">
         <h1>New here?</h1>
         <p>
            If you need any help, kindly send a mail to help@gmail.com and we will attend to you. You can also use the chat box on the log in page
         </p>
      </div>

      <!-- Card 3: Total Classes Held -->
     

    
    
  
  
  </div>
  
  
</section>

  

  </main><!-- End #main -->
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const dateInput = document.getElementById("datepicker");

    const today = new Date();

    // Format day with suffix (st, nd, rd, th)
    function getDaySuffix(day) {
      if (day > 3 && day < 21) return "th"; // 4th - 20th
      switch (day % 10) {
        case 1: return "st";
        case 2: return "nd";
        case 3: return "rd";
        default: return "th";
      }
    }

    const day = today.getDate();
    const suffix = getDaySuffix(day);

    const month = today.toLocaleString("default", { month: "long" });
    const year = today.getFullYear();

    // Final formatted date
    const formattedDate = `${day}${suffix} ${month}, ${year}`;

    dateInput.value = formattedDate;
  });
</script>





  {% endblock content %}
  

templates/dashboard/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Registration</title>

    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">

    <style>
        /* Centering the form */
        body {
            background-color: #f8f9fa;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .card {
            width: 400px;
            border-radius: 12px;
            box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.1);
            padding: 25px;
            background-color: white;
        }

        /* Logo Styling */
        .logo img{
            display: flex;
            align-items: center;
            font-size: 2px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .logo i {
            color: #00c853;
            font-size: 20px;
            margin-right: 5px;
        }

        /* Title Styling */
        .form-title {
            font-size: 20px;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .form-subtitle {
            font-size: 14px;
            color: #777;
            margin-bottom: 15px;
        }

        /* Custom Input Fields */
        .form-control {
            border-radius: 8px;
            font-size: 14px;
            padding: 12px;
        }

        /* Custom Select */
        .form-select {
            border-radius: 8px;
            font-size: 14px;
            padding: 12px;
        }

        /* Button Styling */
        .btn-custom {
            background-color: #24AA4E;
            color: white;
            font-size: 16px;
            font-weight: bold;
            border-radius: 8px;
            padding: 12px;
            width: 100%;
            border: none;
        }

        .btn-custom:hover {
            background-color: #009624;
        }
    </style>
</head>
<body>

    <!-- Registration Form -->
    <div class="card">
        <!-- Logo -->
        <div class="logo">
            <img src="{% static 'asset/img/fred-logo.png' %}" alt="">
        </div>

        <!-- Title -->
        <p class="form-title">Welcome Back!</p>
        <p class="form-subtitle">Kindly Login</p>

        <!-- Form -->
        <form method="POST" >
            {% csrf_token %}

        {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}

            <!-- Email Address -->
            <div class="mb-3">
                <label for="Email address">Reg No.</label>
                <input type="text" name="reg_number" class="form-control" placeholder="Email Address">
            </div>

            <!-- Password -->
            <div class="mb-3">
                <label for="Password">Password</label>
                <input type="password" name="password" class="form-control" placeholder="Password">
            </div>

            <!-- Submit Button -->
            <button type="submit" class="btn btn-custom">Login</button>
        </form>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

templates/dashboard/result_page.html
{% extends "include/base.html" %}

{% block content %}
{% load static %}

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .result-container {
            width: 80%;
            margin: 0 auto;
            border: 1px solid #28a745;
            padding: 20px;
            box-shadow: 2px 2px 5px rgba(0,0,0,0.1);
        }
        h1 {
            text-align: center;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #28a745;
            color: #fff;
        }
        .student-info p {
            margin: 5px 0;
        }
    </style>
<style>
    .check{
        background: #28a745;
        color: #fff;
        padding: 10px 12px;
        border-radius: 5px;
    }
</style>


<main class="main" id="main">

       <div class="result-container">
        <h1>Student Result Sheet</h1>

        <div class="student-info">
            <p><strong>Student Name:</strong>{{ student.name }} </p>
            <p><strong>Semester:</strong> {{ semester }}</p>
            <p><strong>Roll Number:</strong> 001</p>
            <p><strong>Academic Year:</strong> {{ session }}</p>
            <p><strong>Course of Study:</strong> Computer Science</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Course Code</th>
                    <th>Course Title</th>
                    <th>Score</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                {% for r in results %}
  <tr>
    <td>{{ r.course.code }}</td>
    <td>{{ r.course.name }}</td>
    <td>{{ r.score }}</td>
    <td>{{ r.grade }}</td>
  </tr>
  {% endfor %}
            </tbody>
        </table>
    </div>
</main>

{% endblock content %}

templates/include/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - tobe</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'asset/img/Group 1.png' %}" rel="icon">
  <link href="{% static 'asset/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'asset/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/simple-datatables/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>



  <!-- Template Main CSS File -->
  <link href="{% static 'asset/css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'core:index'%}" class="logo d-flex align-items-center">
        <img src="{% static 'asset/img/fred-logo.png' %}" alt="" />
      </a>
    </div>
    <!-- End Logo -->
    <i class="bi bi-list toggle-sidebar-btn"></i>

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
         
            
          
        <li class="nav-item dropdown pe-3">
          <a
            class="nav-link nav-profile d-flex align-items-center pe-0"
            href=""
            data-bs-toggle="dropdown"
          >
            <img
              src="{% static 'asset/img/profile-img.jpg' %}"
              alt="Profile"
              class="rounded-circle"
            />
            <span class="d-none d-md-block ps-2"
              >{{ request.session.student_name }}</span
            > </a
          ><!-- End Profile Iamge Icon -->

          
          <!-- End Profile Dropdown Items -->
        </li>
        <!-- End Profile Nav -->
      </ul>
    </nav>
    <!-- End Icons Navigation -->
  </header>

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link {% if request.path == '/' %} {% else %} collapsed{% endif %}" href="{% url 'core:index'%}">
          <i class="bi bi-grid-fill"></i>
          <span>Overview</span>
        </a>
      </li>
      
     
      <!-- End Dashboard Nav -->
     
     
      <li class="nav-item">
        <a class="nav-link {% if 'check-results' in request.path %} {% else %} collapsed {% endif %} " href="{% url 'core:check_result'%}">
          <i class="bi bi-book"></i>
          <span>Check Result</span>
        </a>
      </li>

       <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'core:logout' %}">
          <i class="bi bi-box-arrow-right"></i>
          <span>logout</span>
        </a>
      </li>
    

    </ul>
  </aside>

  {% block content %}
  {% endblock content %}


  <!-- ======= Footer ======= -->
 {% if messages %}
  <script>
    {% for message in messages %}
      Swal.fire({
        icon: '{% if message.tags == "success" %}success{% else %}error{% endif %}',
        title: '{{ message.tags|capfirst }}',
        text: '{{ message }}',
        confirmButtonColor: '#3085d6'
      });
    {% endfor %}
  </script>
{% endif %}

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'asset/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'asset/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'asset/vendor/chart.js/chart.min.js' %}"></script>
  <script src="{% static 'asset/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'asset/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'asset/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'asset/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'asset/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'asset/js/main.js' %}"></script>

</body>

</html>